package Utils;

public enum Coords {
	ABOVE_FIRST_CARD, ABOVE_SECOND_CARD, ABOVE_THIRD_CARD, ABOVE_FOURTH_CARD, ABOVE_FIFTH_CARD, ABOVE_SIXTH_CARD,
	ABOVE_SEVENTH_CARD, ABOVE_EIGHTH_CARD, FIRST_CARD, SECOND_CARD, THIRD_CARD, FOURTH_CARD, FIFTH_CARD, SIXTH_CARD,
	SEVENTH_CARD, EIGHTH_CARD, OPPONENT_DECK, TWOX_ELIXER,
}
