package Utils;

public enum Images {
	MINER, FIREBALL, GOBLIN_GANG, MINION_HORDE, MORTAR, LOG, BATS, RASCALS, MIRROR, ICE_SPIRIT, SKELETONS, SNOWBALL,
	BARB_BARREL, GOBLINS, ZAP, RAGE, ICE_GOLEM, FIRE_SPIRITS, SPEAR_GOBLINS, KNIGHT, SKELETON_ARMY, BOMBER, HEAL,
	ARCHERS, CLONE, TORNADO, GOBLIN_BARREL, MINIONS, ARROWS, TOMBSTONE, ICE_WIZZARD, CANNON, GUARDS, PRINCESS,
	SKELETON_BARREL, ROYALE_GHOST, BANDIT, DART_GOBLIN, MEGA_MINION, MUSKETEER, HOG_RIDER, LUMBER_JACK, BATTLE_RAM,
	INFERNO_DRAGON, FURNACE, MINI_PEKKA, TESLA, ELECTOR_WIZZARD, VALKYRIE, HUNTER, FREEZ, BABY_DRAGON, BOM_TOWER,
	NIGHT_WITCH, POSION, ZAPPIES, FLYING_MACHINE, DARK_PRINCE, GRAVEYARD, CANNON_CART, ROYALE_HOGS, WIZZARD,
	ELECTRO_DRAGON, GIANT, GOBLIN_HUT, INFERNO_TOWER, PRINCE, EXECUTIONER, BARBARIANS, WITCH, BALOON, BOWLER, XBOW,
	GIANT_SKELETON, ROCKET, ELIXIR_COLLECTOR, LIGHTNING, ROYALE_GIANT, GOBLIN_GIANT, ELITE_BARBARIANS, BARBARIAN_HUT,
	PEKKA, MEGA_KNIGHT, LAVA_HOUND, GOLEM, ROYALE_RECRUITS, THREE_MUSKETEERS, MAGIC_ARCHER,
}
