package Cards;

import java.util.ArrayList;

public class CardFactory {
	public static ArrayList<Card> createCards() {
		ArrayList<Card> cards = new ArrayList<Card>();

		cards.add(new Card("Archers", 3));
		cards.add(new Card("Arrows", 3));
		cards.add(new Card("Babarian barrel", 2));
		cards.add(new Card("Babarian Hut", 5));
		cards.add(new Card("Baby Dragon", 4));
		cards.add(new Card("Balloon", 5));
		cards.add(new Card("Bats", 2));
		cards.add(new Card("Battle Ram", 4));
		cards.add(new Card("Bowler", 5));
		cards.add(new Card("Cannon", 3));
		cards.add(new Card("Dark Prince", 4));
		cards.add(new Card("Dart Goblin", 3));
		cards.add(new Card("Electro Dragon", 5));
		cards.add(new Card("Electro Wizzard", 4));
		cards.add(new Card("Fire Spirits", 2));
		cards.add(new Card("Fireball", 4));
		cards.add(new Card("Furnace", 4));
		cards.add(new Card("Giant Skeleton", 6));
		cards.add(new Card("Goblin Barrel", 3));
		cards.add(new Card("Goblin Gang", 3));
		cards.add(new Card("Golem", 8));
		cards.add(new Card("Graveyard", 5));
		cards.add(new Card("Guards", 3));
		cards.add(new Card("Heal", 3));
		cards.add(new Card("Hog Rider", 4));
		cards.add(new Card("Ice Wizzard", 3));
		cards.add(new Card("Ice Golem", 2));
		cards.add(new Card("Inferno Dragon", 3));
		cards.add(new Card("Inferno Tower", 5));
		cards.add(new Card("Knight", 3));
		cards.add(new Card("Lavahound", 7));
		cards.add(new Card("Log", 2));
		cards.add(new Card("Lumberjack", 4));
		cards.add(new Card("Magical Archer", 4));
		cards.add(new Card("Mega Knight", 7));
		cards.add(new Card("Mega Minion", 3));
		cards.add(new Card("Miner", 3));
		cards.add(new Card("Mini Pekka", 4));
		cards.add(new Card("Minion Horde", 5));
		cards.add(new Card("Minions", 3));
		cards.add(new Card("Mortar", 4));
		cards.add(new Card("Musketeer", 4));
		cards.add(new Card("Posion", 4));
		cards.add(new Card("Prince", 5));
		cards.add(new Card("Princess", 3));
		cards.add(new Card("Rascals", 5));
		cards.add(new Card("Rocket", 6));
		cards.add(new Card("Royale Giant", 6));
		cards.add(new Card("Skeleton Army", 3));
		cards.add(new Card("Skeleton Barrel", 3));
		cards.add(new Card("Spear Goblins", 2));
		cards.add(new Card("tombstone", 3));
		cards.add(new Card("Tornado", 3));
		cards.add(new Card("Valkyrie", 4));
		cards.add(new Card("Witch", 5));
		cards.add(new Card("Wizzard", 5));
		cards.add(new Card("Rage", 2));
		cards.add(new Card("Sparky", 6));
		cards.add(new Card("Ice Golem", 2));
		cards.add(new Card("Zap", 2));
		cards.add(new Card("Elite Barbarians", 6));
		cards.add(new Card("Royale Ghost", 3));
		cards.add(new Card("Executioner", 5));
		cards.add(new Card("Night Witch", 4));
		cards.add(new Card("Goblin Hut", 5));
		cards.add(new Card("Pekka", 7));
		cards.add(new Card("freez", 4));
		cards.add(new Card("Giant", 5));
		cards.add(new Card("Bomber", 3));
		cards.add(new Card("Elixer Collector", 6));
		cards.add(new Card("Ice Spirit", 1));
		cards.add(new Card("Tesla", 4));
		cards.add(new Card("xbow", 6));
		cards.add(new Card("skeletons", 1));
		cards.add(new Card("Bandit", 3));
		return cards;
	}
}
